# -*- coding: utf-8 -*-
"""adder&avg_counter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bUAAoTBjNWjjpiOXI3yP-dPOM-028flk
"""

want_more= True
sum=0
count=0
while want_more == True:
  num = int(input("Enter the number: "))

  if num>=0:
    sum=sum+num
    count=count+1
  else:
    want_more=False
print ("Your sum is ", sum ," and your avg is " , (sum/count))

