# -*- coding: utf-8 -*-
"""Hello_world.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q7pc_aBNH3nkKix75bvtah38586qC5Xa
"""

print("Hello World")

